# Generated by Django 5.2.12 on 2026-03-06 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='name',
            new_name='institution_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='location',
        ),
        migrations.AddField(
            model_name='school',
            name='latitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='school',
            name='longitude',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='school_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='sub_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
