# Generated by Django 5.2.12 on 2026-03-13 21:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_subcounty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimatePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('tmin', models.FloatField()),
                ('tmax', models.FloatField()),
                ('rain', models.FloatField()),
            ],
        ),
    ]
