# Generated by Django 5.2.12 on 2026-03-13 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_climatepoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClimatePoint',
        ),
    ]
