# Generated by Django 5.2.12 on 2026-03-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_delete_climatepoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climaterecord',
            name='timestamp',
        ),
        migrations.AddIndex(
            model_name='climaterecord',
            index=models.Index(db_tablespace='gist', fields=['location'], name='location_idx'),
        ),
    ]
